version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: hawu-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: hawu-rwanda
    volumes:
      - mongodb_data:/data/db
    networks:
      - hawu-network

  server:
    build: ./server
    container_name: hawu-server
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      MONGODB_URI: mongodb://mongodb:27017/hawu-rwanda
      PORT: 5000
      NODE_ENV: production
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      FRONTEND_URL: http://localhost:3000
    depends_on:
      - mongodb
    networks:
      - hawu-network
    volumes:
      - ./server:/app
      - /app/node_modules

volumes:
  mongodb_data:

networks:
  hawu-network:
    driver: bridge
